// Front-end only catalog. Prices are "starting at" figures, not a real cart.
// `code` is a shop SKU used as a print-spec accent throughout the UI.
// `swatch` is a single restrained ink chip (CMYK + flare), never a full-card color.
export const PRODUCTS = [
  {
    id: 'business-cards',
    code: 'BC·16',
    name: 'Business Cards',
    tag: 'Best Seller',
    swatch: '#e5352b',
    price: 29,
    unit: 'per 100',
    stock: '16–32PT',
    blurb: 'Thick soft-touch and spot-gloss stocks. The handshake that stays in the wallet.',
    featured: true,
    details: ['16 & 32pt stocks', 'Soft-touch / gloss', 'Foil & spot UV', 'Rounded corners'],
  },
  {
    id: 'banners',
    code: 'VB·13',
    name: 'Vinyl Banners',
    tag: 'Wide Format',
    swatch: '#2f6bff',
    price: 45,
    unit: 'per unit',
    stock: '13–18OZ',
    blurb: 'Weatherproof 13oz vinyl, hemmed and grommeted. Sized for the whole block.',
    featured: true,
    details: ['13 & 18oz vinyl', 'Indoor / outdoor', 'Grommets & pockets', 'Up to 10ft wide'],
  },
  {
    id: 'apparel',
    code: 'AP·DTF',
    name: 'Custom Apparel',
    tag: 'DTF · Screen',
    swatch: '#6b7683',
    price: 18,
    unit: 'per piece',
    stock: 'DTF/SCR',
    blurb: 'DTF and screen-printed tees, hoodies, and team apparel. Your design, your colors.',
    featured: true,
    details: ['DTF full-color', 'Screen print', 'Embroidery', 'Tees · hoodies · caps'],
  },
  {
    id: 'stickers',
    code: 'ST·DC',
    name: 'Stickers & Decals',
    tag: 'Die-Cut',
    swatch: '#b81f16',
    price: 22,
    unit: 'per 50',
    stock: 'VINYL',
    blurb: 'Die-cut, holographic and weatherproof vinyl. Built to survive the street.',
    featured: true,
    details: ['Die & kiss-cut', 'Holographic', 'Weatherproof', 'Sheets or rolls'],
  },
  {
    id: 'flyers',
    code: 'FL·100',
    name: 'Flyers & Posters',
    tag: 'Promo',
    swatch: '#e5352b',
    price: 34,
    unit: 'per 250',
    stock: '100LB',
    blurb: 'Full-bleed, high-ink flyers and posters engineered to pop off the pole.',
    featured: false,
    details: ['100lb gloss/matte', 'Up to 24×36', 'Same-day rush', 'Both sides'],
  },
  {
    id: 'signs',
    code: 'SG·CORO',
    name: 'Signs & Boards',
    tag: 'Rigid',
    swatch: '#2f6bff',
    price: 59,
    unit: 'per unit',
    stock: 'ALUM',
    blurb: 'Coroplast, aluminum and foam board. Storefront presence, locked in.',
    featured: false,
    details: ['Coroplast/aluminum', 'A-frames', 'Yard signs', 'Mounted board'],
  },
  {
    id: 'packaging',
    code: 'PK·BOX',
    name: 'Packaging',
    tag: 'Bespoke',
    swatch: '#6b7683',
    price: 89,
    unit: 'per run',
    stock: 'SBS',
    blurb: 'Custom boxes, mailers and labels that turn the unboxing into a moment.',
    featured: false,
    details: ['Mailer boxes', 'Custom labels', 'Tissue & tape', 'Small batch'],
  },
  {
    id: 'menus',
    code: 'MN·LAM',
    name: 'Menus & Prints',
    tag: 'Hospitality',
    swatch: '#b81f16',
    price: 39,
    unit: 'per 100',
    stock: 'LAM',
    blurb: 'Laminated menus, table tents and prints built to survive a Friday service.',
    featured: false,
    details: ['Laminated/rigid', 'Table tents', 'Loyalty cards', 'Waterproof'],
  },
];

export const FEATURED_PRODUCTS = PRODUCTS.filter((p) => p.featured);
