// Front-end only catalog. Prices are "starting at" marketing figures, not a real cart.
export const PRODUCTS = [
  {
    id: 'business-cards',
    name: 'Business Cards',
    tag: 'Best Seller',
    accent: 'magenta',
    price: 29,
    unit: '/ 100',
    blurb: 'Thick 16pt stock, soft-touch or spot-gloss. The handshake that sticks.',
    featured: true,
    details: [
      '16pt & 32pt stocks',
      'Matte / soft-touch / gloss',
      'Foil & spot UV',
      'Rounded corners',
    ],
  },
  {
    id: 'banners',
    name: 'Vinyl Banners',
    tag: 'Big & Bold',
    accent: 'cyan',
    price: 45,
    unit: '/ each',
    blurb: 'Weatherproof 13oz vinyl, hemmed and grommeted. Loud enough for the whole block.',
    featured: true,
    details: [
      '13oz & 18oz vinyl',
      'Indoor / outdoor',
      'Grommets & pole pockets',
      'Up to 10ft wide',
    ],
  },
  {
    id: 'apparel',
    name: 'Custom Apparel',
    tag: 'DTF / Screen',
    accent: 'acid',
    price: 18,
    unit: '/ shirt',
    blurb: 'DTF and screen-printed tees, hoodies and crews. Your crew, your colors.',
    featured: true,
    details: ['DTF full-color', 'Screen print', 'Embroidery', 'Tees · hoodies · caps'],
  },
  {
    id: 'stickers',
    name: 'Stickers & Decals',
    tag: 'Slap Ready',
    accent: 'sunset',
    price: 22,
    unit: '/ 50',
    blurb: 'Die-cut, holographic, and weatherproof vinyl. Tag the town legally.',
    featured: true,
    details: ['Die-cut & kiss-cut', 'Holographic & clear', 'Weatherproof vinyl', 'Sheets or rolls'],
  },
  {
    id: 'flyers',
    name: 'Flyers & Posters',
    tag: 'Street Promo',
    accent: 'gold',
    price: 34,
    unit: '/ 250',
    blurb: 'Full-bleed, high-ink flyers and posters that pop off the pole.',
    featured: false,
    details: [
      '100lb gloss / matte',
      'Up to 24x36 posters',
      'Same-day rush',
      'Full color both sides',
    ],
  },
  {
    id: 'signs',
    name: 'Signs & Boards',
    tag: 'Store Front',
    accent: 'cyan',
    price: 59,
    unit: '/ each',
    blurb: 'Coroplast, aluminum, and foam board. Storefront presence on lock.',
    featured: false,
    details: ['Coroplast & aluminum', 'A-frames', 'Yard signs', 'Mounted foam board'],
  },
  {
    id: 'packaging',
    name: 'Packaging',
    tag: 'Unbox It',
    accent: 'magenta',
    price: 89,
    unit: '/ run',
    blurb: 'Custom boxes, mailers, and labels that make the unboxing a moment.',
    featured: false,
    details: ['Mailer & shipping boxes', 'Custom labels', 'Tissue & tape', 'Small-batch runs'],
  },
  {
    id: 'menus',
    name: 'Menus & Prints',
    tag: 'Hospitality',
    accent: 'acid',
    price: 39,
    unit: '/ 100',
    blurb: 'Laminated menus, table tents, and hospitality prints built to survive service.',
    featured: false,
    details: ['Laminated & rigid', 'Table tents', 'Loyalty cards', 'Waterproof options'],
  },
];

export const FEATURED_PRODUCTS = PRODUCTS.filter((p) => p.featured);

export const ACCENT_CLASS = {
  magenta: {
    text: 'text-neon-magenta',
    ring: 'hover:border-magenta/60 hover:shadow-neon-magenta',
    dot: 'bg-magenta',
    chip: 'bg-magenta/15 text-magenta border-magenta/30',
  },
  cyan: {
    text: 'text-neon-cyan',
    ring: 'hover:border-cyan/60 hover:shadow-neon-cyan',
    dot: 'bg-cyan',
    chip: 'bg-cyan/15 text-cyan border-cyan/30',
  },
  acid: {
    text: 'text-neon-acid',
    ring: 'hover:border-acid/60 hover:shadow-neon-acid',
    dot: 'bg-acid',
    chip: 'bg-acid/15 text-acid border-acid/30',
  },
  sunset: {
    text: 'text-sunset',
    ring: 'hover:border-sunset/60',
    dot: 'bg-sunset',
    chip: 'bg-sunset/15 text-sunset border-sunset/30',
  },
  gold: {
    text: 'text-gold',
    ring: 'hover:border-gold/60',
    dot: 'bg-gold',
    chip: 'bg-gold/15 text-gold border-gold/30',
  },
};
